[BE] Feat: DB Model Create &  Migration
boostcamp-2020/IssueTracker-14 pull request #30
Opened 2020-10-28 10:00 UTC by 2-one-week

#29

2020-10-28 23:16 UTC, lcpnine reviewed
server/db 폴더의 migration 파일들과 models 파일들에 대해
```
"use strict" 

module.exports {
   ...
}
```
과 같이 일관성있는 따옴표와 줄바꿈이 있으면 좋을 것 같습니다.

2020-10-29 04:49 UTC, Zinyon requested changes

2020-10-29 04:49 UTC, Zinyon commented on server/db/models/issue.js
> +      // define association here
어제 까먹은 부분이 있었네요!
이 부분에 각 모델 객체 파일마다 association 설정 해줘야 할 것 같습니다.
지금은 migration에만 association이 적용되어 mySQL에는 반영이 되었지만
ORM 모델 객체에는 assocation이 반영되지 않아 나중에 오류가 날 수 있습니다

2020-10-29 05:29 UTC, Zinyon approved these changes

2020-10-29 05:29 UTC, 2-one-week commented on server/db/models/issue.js
> +      // define association here
수정했습니다

2020-10-29 05:29 UTC, merged